# NodePort type service deploy example
# after the deploy you can reach the application on the IP of the node, like curl http://<node_ip>:30001
# for example on Docker Desktop it's curl http://localhost:30001
#
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30001
  selector:
    app: nginx
    purpose: template
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    purpose: template
spec:
  containers:
    - image: nginx
      name: nginx
