apiVersion: v1
kind: Pod
metadata:
  name: keep-alive
  labels:
    app: keep-alive
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "--"]
    args: ["while true; do sleep 30; done;"]