apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: busybox
spec:
  template:
    metadata:
      name: busybox
      labels:
        app: busybox
    spec:
      containers:
      - image: busybox
        name: busybox
  replicas: 2
  selector:
    matchLabels:
      app: busybox
